[build]
builder = "nixpacks"
buildCommand = "cd backend/salud_metal_app_back && npm install"

[deploy]
startCommand = "cd backend/salud_metal_app_back && npm start"

[variables]
NIXPACKS_NODE_VERSION = "18"
